<a href="https://colab.research.google.com/github/Eric-Schwinn-Lima/Tech-Challenge---NPS/blob/main/NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### EXPLORANDO OS FATORES QUE MAIS IMPACTAM NO ÍNDICE DE SATISFAÇÃO DO CLIENTE (NPS)


---


**● Qual problema de negócio está sendo resolvido**- •	Os dados de NPS são coletados após a finalização de todo o processo de compra, o que implica em falta de poder de tomada de decisão voltado para evitar a ocorrência dos problemas, já que somente se tem a visibilidade após o problema já ter acontecido.

**● Por que o NPS é importante para um e-commerce?**


---


O indicador de experiência do cliente, é uma métrica que valida a satisfação entre os clientes através de pesquisas. Onde o cliente que apresenta estar muito satisfeito com a marca, tende a manter fidelidade e promover a marca para que outras pessoas possam se tornar possíveis clientes. Ao mesmo tempo em que, clientes que se apresentam insatisfeitos, tendem a não utilizar mais da marca e até mesmo difamar para o público.
Tendo um NPS bem claro, é possível estudar abordagens buscando alternativas para contornar casos de insatisfação por parte dos clientes, visando uma reversão nos possíveis casos de perda de clientela por experiências ruins.

**● Quais áreas poderiam se beneficiar desses insights? Exemplos:**


---



•	**Logística**: A logística através desses insights, pode reanalisar todo seu processo em busca de entender como melhorar a satisfação do cliente final.
Essa reestruturação, pode se dar no processo de expedição, no transporte das mercadorias, no desenho das rotas, nos prazos de entrega e até mesmo na análise das transportadoras, com possibilidade de identificar um possível gargalo no processo.

•	**Produto/Fábrica:** Pode identificar falhas no processo de produção que podem ser convertidas em melhorias que permitam a criação de produtos com maior qualidade ou que agradem as exigências por parte do cliente.

•	**Pricing:** Com o indicador NPS e feedbacks dos clientes, a área de pricing pode rever seus preços de venda, e identificar se o valor cobrado, é justo, condiz com o mercado, ou está sendo considerado incorretamente.

### ANÁLISE EXPLORATÓRIA DE DADOS (EDA)

##Importando Bibliotecas

In [ ]:
#exploração e manipulação de dados
import pandas as pd
import numpy as np

#gráficos
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

plt.style.use('default')
sns.set(style="whitegrid")

##Importando Dataset

In [ ]:
df = pd.read_csv('desafio_nps_fase_1.csv')

In [ ]:
df.head()

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

##Filtro dos Nomes das Colunas

In [ ]:
df.columns

Index(['customer_id', 'customer_age', 'customer_region',
       'customer_tenure_months', 'order_id', 'order_value', 'items_quantity',
       'discount_value', 'payment_installments', 'delivery_time_days',
       'delivery_delay_days', 'freight_value', 'delivery_attempts',
       'customer_service_contacts', 'resolution_time_days', 'nps_score',
       'repeat_purchase_30d', 'complaints_count', 'csat_internal_score'],
      dtype='object')

## Traduzindo O Nome das Colunas

In [ ]:
df_nps = df [['customer_id','customer_age','customer_region',
              'customer_tenure_months','order_id','order_value', 'items_quantity',
              'discount_value', 'payment_installments', 'delivery_time_days',
              'delivery_delay_days', 'freight_value', 'delivery_attempts',
              'customer_service_contacts', 'resolution_time_days', 'nps_score',
              'repeat_purchase_30d', 'complaints_count', 'csat_internal_score']]

df_nps.columns =['id_cliente',
    'idade_cliente',
    'regiao_cliente',
    'meses_como_cliente',
    'id_pedido',
    'valor_pedido',
    'quantidade_itens',
    'valor_desconto',
    'parcelas_pagamento',
    'tempo_entrega_dias',
    'dias_atraso_entrega',
    'valor_frete',
    'tentativas_entrega',
    'contatos_sac',
    'tempo_resolucao_dias',
    'nota_nps',
    'recompra_30d',
    'quantidade_reclamacoes',
    'nota_interna_csat'
]

In [ ]:
df_nps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_cliente              2500 non-null   int64
 1   idade_cliente           2500 non-null   int64
 2   regiao_cliente          2500 non-null   object
 3   meses_como_cliente      2500 non-null   int64
 4   id_pedido               2500 non-null   int64
 5   valor_pedido            2500 non-null   float64
 6   quantidade_itens        2500 non-null   int64
 7   valor_desconto          2500 non-null   float64
 8   parcelas_pagamento      2500 non-null   int64
 9   tempo_entrega_dias      2500 non-null   int64
 10  dias_atraso_entrega     2500 non-null   int64
 11  valor_frete             2500 non-null   float64
 12  tentativas_entrega      2500 non-null   int64
 13  contatos_sac            2500 non-null   int64
 14  tempo_resolucao_dias    2500 non-null   int64
 15  nota_nps                2500 non-null   float64
 16  recompra_30d            2500 non-null   int64
 17  quantidade_reclamacoes  2500 non-null   int64
 18  nota_interna_csat       2500 non-null   float64
dtypes: float64(5), int64(13), object(1)
memory usage: 371.2+ KB

In [ ]:
df_nps.shape
print(f'Tamanho do dataset (Linhas x Colunas): {df.shape}')

Tamanho do dataset (Linhas x Colunas): (2500, 19)

In [ ]:
df_nps.dtypes

id_cliente                  int64
idade_cliente               int64
regiao_cliente             object
meses_como_cliente          int64
id_pedido                   int64
valor_pedido              float64
quantidade_itens            int64
valor_desconto            float64
parcelas_pagamento          int64
tempo_entrega_dias          int64
dias_atraso_entrega         int64
valor_frete               float64
tentativas_entrega          int64
contatos_sac                int64
tempo_resolucao_dias        int64
nota_nps                  float64
recompra_30d                int64
quantidade_reclamacoes      int64
nota_interna_csat         float64
dtype: object

#Validar Valores Nulos

In [ ]:
valores_nulos = df_nps.isnull().sum()
print(f'Quantidade de nulos no dataset: \n{valores_nulos}')

Quantidade de nulos no dataset:
id_cliente                0
idade_cliente             0
regiao_cliente            0
meses_como_cliente        0
id_pedido                 0
valor_pedido              0
quantidade_itens          0
valor_desconto            0
parcelas_pagamento        0
tempo_entrega_dias        0
dias_atraso_entrega       0
valor_frete               0
tentativas_entrega        0
contatos_sac              0
tempo_resolucao_dias      0
nota_nps                  0
recompra_30d              0
quantidade_reclamacoes    0
nota_interna_csat         0
dtype: int64

In [ ]:
df_nps.head()

,id_cliente,idade_cliente,regiao_cliente,meses_como_cliente,id_pedido,valor_pedido,quantidade_itens,valor_desconto,parcelas_pagamento,tempo_entrega_dias,dias_atraso_entrega,valor_frete,tentativas_entrega,contatos_sac,tempo_resolucao_dias,nota_nps,recompra_30d,quantidade_reclamacoes,nota_interna_csat
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

In [ ]:
df_nps.describe().T.round(2)

,count,mean,std,min,25%,50%,75%,max
id_cliente,2500.0,1250.50,721.83,1.00,625.75,1250.50,1875.25,2500.00
idade_cliente,2500.0,43.40,14.89,18.00,31.00,43.00,56.00,69.00
meses_como_cliente,2500.0,61.32,34.48,1.00,31.00,62.00,91.00,119.00
id_pedido,2500.0,51250.50,721.83,50001.00,50625.75,51250.50,51875.25,52500.00
valor_pedido,2500.0,434.26,289.77,7.76,220.24,375.52,577.29,1983.81
quantidade_itens,2500.0,3.47,1.69,1.00,2.00,3.00,5.00,6.00
valor_desconto,2500.0,29.75,29.23,0.02,8.88,20.94,40.83,230.33
parcelas_pagamento,2500.0,6.00,3.16,1.00,3.00,6.00,9.00,11.00
tempo_entrega_dias,2500.0,8.02,3.77,2.00,5.00,8.00,11.00,14.00
dias_atraso_entrega,2500.0,2.19,1.45,0.00,1.00,2.00,3.00,8.00
valor_frete,2500.0,38.22,12.08,2.62,29.93,38.50,46.27,76.13
tentativas_entrega,2500.0,2.01,0.82,1.00,1.00,2.00,3.00,3.00
contatos_sac,2500.0,1.52,1.23,0.00,1.00,1.00,2.00,7.00
tempo_resolucao_dias,2500.0,5.49,3.46,0.00,2.00,6.00,8.00,11.00
nota_nps,2500.0,4.38,2.51,0.00,2.60,4.40,6.10,10.00
recompra_30d,2500.0,0.09,0.28,0.00,0.00,0.00,0.00,1.00
quantidade_reclamacoes,2500.0,4.15,1.78,0.00,3.00,4.00,5.00,11.00
nota_interna_csat,2500.0,2.94,2.38,0.00,0.70,2.80,4.80,10.00

## Buscando os valores mínima, média e máxima para cada coluna

In [ ]:
df_nps[["idade_cliente", "meses_como_cliente", "valor_pedido",
    "quantidade_itens", "valor_desconto", "parcelas_pagamento",
    "tempo_entrega_dias", "dias_atraso_entrega", "tentativas_entrega",
    "tempo_resolucao_dias", "nota_nps"]].agg(["min", "mean", "max"]).round(2).T

                        min    mean      max
idade_cliente         18.00   43.40    69.00
meses_como_cliente     1.00   61.32   119.00
valor_pedido           7.76  434.26  1983.81
quantidade_itens       1.00    3.47     6.00
valor_desconto         0.02   29.75   230.33
parcelas_pagamento     1.00    6.00    11.00
tempo_entrega_dias     2.00    8.02    14.00
dias_atraso_entrega    0.00    2.19     8.00
tentativas_entrega     1.00    2.01     3.00
tempo_resolucao_dias   0.00    5.49    11.00
nota_nps               0.00    4.38    10.00

In [ ]:
df_nps["classificacao_nps"] = 'neutro'
df_nps.loc[df_nps['nota_nps'] <=6, "classificacao_nps"] = 'detrator'
df_nps.loc[df_nps['nota_nps'] >= 9, "classificacao_nps" ] = 'promotor'

In [ ]:
df_nps.sort_values("nota_nps", ascending=True).head(5)

,id_cliente,idade_cliente,regiao_cliente,meses_como_cliente,id_pedido,valor_pedido,quantidade_itens,valor_desconto,parcelas_pagamento,tempo_entrega_dias,dias_atraso_entrega,valor_frete,tentativas_entrega,contatos_sac,tempo_resolucao_dias,nota_nps,recompra_30d,quantidade_reclamacoes,nota_interna_csat,classificacao_nps
36,37,53,Norte,23,50037,557.80,4,0.31,9,8,5,44.25,1,3,10,0.0,0,5,0.0,detrator
32,33,65,Norte,57,50033,385.12,1,5.05,6,13,4,43.54,2,2,5,0.0,0,4,0.7,detrator
68,69,24,Sul,45,50069,1402.67,1,43.56,9,8,4,51.51,2,5,3,0.0,0,9,0.0,detrator
61,62,62,Norte,81,50062,42.28,1,39.12,9,3,4,47.80,3,1,11,0.0,0,5,0.0,detrator
69,70,32,Nordeste,82,50070,639.53,4,66.26,3,3,2,35.79,3,3,11,0.0,0,8,0.0,detrator

In [ ]:
colunas_numericas = ["idade_cliente", "meses_como_cliente", "valor_pedido",
    "quantidade_itens", "valor_desconto", "parcelas_pagamento",
    "tempo_entrega_dias", "dias_atraso_entrega", "tentativas_entrega",
    "contatos_sac", "tempo_resolucao_dias"]

In [ ]:
nps_geral = df_nps.groupby("classificacao_nps")[colunas_numericas].mean()
display(nps_geral)

,idade_cliente,meses_como_cliente,valor_pedido,quantidade_itens,valor_desconto,parcelas_pagamento,tempo_entrega_dias,dias_atraso_entrega,tentativas_entrega,contatos_sac,tempo_resolucao_dias
classificacao_nps,,,,,,,,,,,
detrator,43.309562,61.575365,428.985446,3.494868,29.631248,5.968125,7.995678,2.534306,1.992977,1.694219,5.793625
neutro,43.645640,60.111317,445.469443,3.354360,29.525176,6.166976,8.129870,1.294991,2.018553,1.092764,4.792208
promotor,43.627273,63.000000,468.084182,3.636364,32.750364,5.809091,7.936364,0.718182,2.154545,0.672727,3.700000

## Criação de um Dataframe filtrando somente os 'Detratores'

In [ ]:
df_detratores = df_nps[df_nps['classificacao_nps'] == "detrator"]
detratores_resumo = df_detratores[colunas_numericas].describe().round(2)
display(detratores_resumo)

,idade_cliente,meses_como_cliente,valor_pedido,quantidade_itens,valor_desconto,parcelas_pagamento,tempo_entrega_dias,dias_atraso_entrega,tentativas_entrega,contatos_sac,tempo_resolucao_dias
count,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00,1851.00
mean,43.31,61.58,428.99,3.49,29.63,5.97,8.00,2.53,1.99,1.69,5.79
std,14.84,34.71,287.73,1.69,28.76,3.18,3.79,1.43,0.81,1.27,3.42
min,18.00,1.00,7.76,1.00,0.02,1.00,2.00,0.00,1.00,0.00,0.00
25%,31.00,32.00,215.56,2.00,8.96,3.00,5.00,1.00,1.00,1.00,3.00
50%,43.00,63.00,374.01,3.00,20.80,6.00,8.00,2.00,2.00,2.00,6.00
75%,56.00,91.00,569.68,5.00,41.04,9.00,11.00,3.00,3.00,2.00,9.00
max,69.00,119.00,1915.89,6.00,230.33,11.00,14.00,8.00,3.00,7.00,11.00

In [ ]:
nps_porcentagem = df_nps['classificacao_nps'].value_counts(normalize=True) * 100
display(nps_porcentagem)

classificacao_nps
detrator    74.04
neutro      21.56
promotor     4.40
Name: proportion, dtype: float64